### ISSUE TITLE
Installation Steps

### ISSUE THREAD

**Issue by abhinavmodi** [avinetworks/avi_ansible_modules#5]
The installation steps mention 

tar -xvf master.tar.gz -C /etc/ansible/library

This creates a directory "avi_ansible_modules-master/" under /etc/ansible/library, with the modules.

These modules then need to be moved into /etc/ansible/library/avi manually.

Suggest that either the packaging be rectified, or documentation changed to reflect this.

**Comment by ericsysmin** [comment]
Yea, don't do that, these should auto populate on build into the role, using the role is the desired way. This repo is basically just a placeholder for inclusion in other repositories.

**Comment by ericsysmin** [comment]
I will talk with @grastogi23 today since we're at AnsibleFest and come up with a better way, or possibly hiding this repo
